// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Persistence;

#nullable disable

namespace Nexus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260824194033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Domain.Entities.Admin.Nummernkreis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("NaechsteNummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Jahr")
                        .IsUnique()
                        .HasFilter("[Jahr] IS NOT NULL");

                    b.ToTable("Nummernkreise", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ean")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EinheitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Einkaufspreis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<bool>("Gesperrt")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Gewicht")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("HatSeriennummern")
                        .HasColumnType("bit");

                    b.Property<bool>("IstLagerartikel")
                        .HasColumnType("bit");

                    b.Property<decimal>("Listenpreis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Mindestbestand")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("MwStSatzId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Artikelnummer")
                        .IsUnique();

                    b.HasIndex("EinheitId");

                    b.HasIndex("MwStSatzId");

                    b.ToTable("Artikel", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.ArtikelPreis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbMenge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("PreislisteId", "ArtikelId", "AbMenge")
                        .IsUnique();

                    b.ToTable("ArtikelPreise", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Einheit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NachkommaStellen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kuerzel")
                        .IsUnique();

                    b.ToTable("Einheiten", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ansprechpartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DebitorenkontoNr")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailRechnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kreditlimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kundennummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Liefersperre")
                        .HasColumnType("bit");

                    b.Property<string>("Notiz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal>("RabattProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UStIdNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZahlungsbedingungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kundennummer")
                        .IsUnique();

                    b.HasIndex("PreislisteId");

                    b.HasIndex("ZahlungsbedingungId");

                    b.ToTable("Kunden", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Lieferant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ansprechpartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<int?>("KreditorenkontoNr")
                        .HasColumnType("int");

                    b.Property<string>("Lieferantennummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notiz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UStIdNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZahlungsbedingungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Lieferantennummer")
                        .IsUnique();

                    b.HasIndex("ZahlungsbedingungId");

                    b.ToTable("Lieferanten", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.MwStSatz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("date");

                    b.Property<decimal>("Satz")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SteuerSchluessel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MwStSaetze", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Preisliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("GueltigVon")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Preislisten", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Versandart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Kosten")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Versandarten", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Zahlungsbedingung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SkontoProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SkontoTage")
                        .HasColumnType("int");

                    b.Property<int>("ZielTage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zahlungsbedingungen", (string)null);
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Artikel", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Einheit", "Einheit")
                        .WithMany()
                        .HasForeignKey("EinheitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Stammdaten.MwStSatz", "MwStSatz")
                        .WithMany()
                        .HasForeignKey("MwStSatzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Einheit");

                    b.Navigation("MwStSatz");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.ArtikelPreis", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Preisliste", "Preisliste")
                        .WithMany("Preise")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Preisliste");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Kunde", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Preisliste", "Preisliste")
                        .WithMany()
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Zahlungsbedingung", "Zahlungsbedingung")
                        .WithMany()
                        .HasForeignKey("ZahlungsbedingungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Nexus.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("KundeId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Strasse");

                            b1.HasKey("KundeId");

                            b1.ToTable("Kunden");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Preisliste");

                    b.Navigation("Zahlungsbedingung");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Lieferant", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Stammdaten.Zahlungsbedingung", "Zahlungsbedingung")
                        .WithMany()
                        .HasForeignKey("ZahlungsbedingungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Nexus.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("LieferantId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Strasse");

                            b1.HasKey("LieferantId");

                            b1.ToTable("Lieferanten");

                            b1.WithOwner()
                                .HasForeignKey("LieferantId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Zahlungsbedingung");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Stammdaten.Preisliste", b =>
                {
                    b.Navigation("Preise");
                });
#pragma warning restore 612, 618
        }
    }
}
