// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milet.Infrastructure.Persistence;

#nullable disable

namespace Milet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiletDbContext))]
    [Migration("20260826155229_LagerLieferschein")]
    partial class LagerLieferschein
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Milet.Domain.Entities.Admin.Firmenstamm", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firmenname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UStIdNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Firmenstamm", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Admin.Nummernkreis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("NaechsteNummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Jahr")
                        .IsUnique()
                        .HasFilter("[Jahr] IS NOT NULL");

                    b.ToTable("Nummernkreise", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Finanzen.OffenerPosten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BelegId")
                        .HasColumnType("int");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Faelligkeit")
                        .HasColumnType("date");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<bool>("Mahnsperre")
                        .HasColumnType("bit");

                    b.Property<int>("Mahnstufe")
                        .HasColumnType("int");

                    b.Property<decimal>("OffenerBetrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BelegId")
                        .IsUnique();

                    b.ToTable("OffenePosten", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.ArtikelBestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("LagerortId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("LagerortId");

                    b.HasIndex("ArtikelId", "LagerortId")
                        .IsUnique();

                    b.ToTable("ArtikelBestaende", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.BelegPositionSeriennummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BelegPositionId")
                        .HasColumnType("int");

                    b.Property<int>("SeriennummerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeriennummerId");

                    b.HasIndex("BelegPositionId", "SeriennummerId")
                        .IsUnique();

                    b.ToTable("BelegPositionSeriennummern", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Inventur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<int>("LagerortId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LagerortId");

                    b.ToTable("Inventuren", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.InventurPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("InventurId")
                        .HasColumnType("int");

                    b.Property<decimal?>("IstMenge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("SollMenge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("InventurId");

                    b.ToTable("InventurPositionen", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Lagerbewegung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int?>("BelegPositionId")
                        .HasColumnType("int");

                    b.Property<int?>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("LagerortId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("SeriennummerId")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BelegPositionId");

                    b.HasIndex("LagerortId");

                    b.HasIndex("SeriennummerId");

                    b.HasIndex("ArtikelId", "LagerortId");

                    b.ToTable("Lagerbewegungen", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Lagerort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Lagerorte", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Seriennummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<int?>("LagerortId")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LagerortId");

                    b.HasIndex("ArtikelId", "Nummer")
                        .IsUnique();

                    b.ToTable("Seriennummern", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ean")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EinheitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Einkaufspreis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<bool>("Gesperrt")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Gewicht")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("HatSeriennummern")
                        .HasColumnType("bit");

                    b.Property<bool>("IstLagerartikel")
                        .HasColumnType("bit");

                    b.Property<decimal>("Listenpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mindestbestand")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("MwStSatzId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Artikelnummer")
                        .IsUnique();

                    b.HasIndex("EinheitId");

                    b.HasIndex("MwStSatzId");

                    b.ToTable("Artikel", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.ArtikelPreis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AbMenge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("PreislisteId", "ArtikelId", "AbMenge")
                        .IsUnique();

                    b.ToTable("ArtikelPreise", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Einheit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NachkommaStellen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kuerzel")
                        .IsUnique();

                    b.ToTable("Einheiten", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ansprechpartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DebitorenkontoNr")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailRechnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kreditlimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kundennummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Liefersperre")
                        .HasColumnType("bit");

                    b.Property<string>("Notiz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal>("RabattProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UStIdNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZahlungsbedingungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kundennummer")
                        .IsUnique();

                    b.HasIndex("PreislisteId");

                    b.HasIndex("ZahlungsbedingungId");

                    b.ToTable("Kunden", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Lieferant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ansprechpartner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<int?>("KreditorenkontoNr")
                        .HasColumnType("int");

                    b.Property<string>("Lieferantennummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notiz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UStIdNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZahlungsbedingungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Lieferantennummer")
                        .IsUnique();

                    b.HasIndex("ZahlungsbedingungId");

                    b.ToTable("Lieferanten", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.MwStSatz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("date");

                    b.Property<decimal>("Satz")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SteuerSchluessel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MwStSaetze", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Preisliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("GueltigVon")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Preislisten", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Versandart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Kosten")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Versandarten", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Zahlungsbedingung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SkontoProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SkontoTage")
                        .HasColumnType("int");

                    b.Property<int>("ZielTage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zahlungsbedingungen", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Beleg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BelegDatum")
                        .HasColumnType("date");

                    b.Property<string>("BelegNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BelegTyp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ErstelltVonId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Faelligkeit")
                        .HasColumnType("date");

                    b.Property<string>("Fusstext")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("GeaendertAm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeaendertVonId")
                        .HasColumnType("int");

                    b.Property<string>("Kopftext")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Leistungsdatum")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SummeBrutto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SummeMwSt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SummeNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ZahlungsbedingungSkontoProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ZahlungsbedingungSkontoTage")
                        .HasColumnType("int");

                    b.Property<int>("ZahlungsbedingungZielTage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.HasIndex("BelegTyp", "BelegNummer")
                        .IsUnique()
                        .HasFilter("[BelegNummer] <> ''");

                    b.ToTable("Belege", (string)null);

                    b.HasDiscriminator<string>("BelegTyp").HasValue("Beleg");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.BelegPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtikelId")
                        .HasColumnType("int");

                    b.Property<int>("BelegId")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EinheitKuerzel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Einzelpreis")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GesamtNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LagerortId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("MwStSatzId")
                        .HasColumnType("int");

                    b.Property<decimal>("MwStSatzWert")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PositionsNr")
                        .HasColumnType("int");

                    b.Property<int>("PositionsTyp")
                        .HasColumnType("int");

                    b.Property<decimal>("RabattProzent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("SteuerSchluessel")
                        .HasColumnType("int");

                    b.Property<int?>("UrsprungsPositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId");

                    b.HasIndex("BelegId");

                    b.HasIndex("LagerortId");

                    b.HasIndex("MwStSatzId");

                    b.HasIndex("UrsprungsPositionId");

                    b.ToTable("BelegPositionen", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.BelegSteuerSumme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BelegId")
                        .HasColumnType("int");

                    b.Property<decimal>("MwStBetrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MwStSatzWert")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("NettoSumme")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SteuerSchluessel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BelegId");

                    b.ToTable("BelegSteuerSummen", (string)null);
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Angebot", b =>
                {
                    b.HasBaseType("Milet.Domain.Entities.Verkauf.Beleg");

                    b.HasDiscriminator().HasValue("Angebot");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Auftrag", b =>
                {
                    b.HasBaseType("Milet.Domain.Entities.Verkauf.Beleg");

                    b.HasDiscriminator().HasValue("Auftrag");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Lieferschein", b =>
                {
                    b.HasBaseType("Milet.Domain.Entities.Verkauf.Beleg");

                    b.HasDiscriminator().HasValue("Lieferschein");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Rechnung", b =>
                {
                    b.HasBaseType("Milet.Domain.Entities.Verkauf.Beleg");

                    b.HasDiscriminator().HasValue("Rechnung");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Admin.Firmenstamm", b =>
                {
                    b.OwnsOne("Milet.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("FirmenstammId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Strasse");

                            b1.HasKey("FirmenstammId");

                            b1.ToTable("Firmenstamm");

                            b1.WithOwner()
                                .HasForeignKey("FirmenstammId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });

            modelBuilder.Entity("Milet.Domain.Entities.Finanzen.OffenerPosten", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Verkauf.Beleg", "Beleg")
                        .WithMany()
                        .HasForeignKey("BelegId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beleg");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.ArtikelBestand", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Lagerort", "Lagerort")
                        .WithMany()
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Lagerort");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.BelegPositionSeriennummer", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Verkauf.BelegPosition", "BelegPosition")
                        .WithMany()
                        .HasForeignKey("BelegPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Seriennummer", "Seriennummer")
                        .WithMany()
                        .HasForeignKey("SeriennummerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BelegPosition");

                    b.Navigation("Seriennummer");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Inventur", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Lager.Lagerort", "Lagerort")
                        .WithMany()
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lagerort");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.InventurPosition", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Inventur", "Inventur")
                        .WithMany("Positionen")
                        .HasForeignKey("InventurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Inventur");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Lagerbewegung", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Verkauf.BelegPosition", "BelegPosition")
                        .WithMany()
                        .HasForeignKey("BelegPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Milet.Domain.Entities.Lager.Lagerort", "Lagerort")
                        .WithMany()
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Seriennummer", "Seriennummer")
                        .WithMany()
                        .HasForeignKey("SeriennummerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artikel");

                    b.Navigation("BelegPosition");

                    b.Navigation("Lagerort");

                    b.Navigation("Seriennummer");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Seriennummer", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Lagerort", "Lagerort")
                        .WithMany()
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artikel");

                    b.Navigation("Lagerort");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Artikel", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Einheit", "Einheit")
                        .WithMany()
                        .HasForeignKey("EinheitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Stammdaten.MwStSatz", "MwStSatz")
                        .WithMany()
                        .HasForeignKey("MwStSatzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Einheit");

                    b.Navigation("MwStSatz");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.ArtikelPreis", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Stammdaten.Preisliste", "Preisliste")
                        .WithMany("Preise")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Preisliste");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Kunde", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Preisliste", "Preisliste")
                        .WithMany()
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Milet.Domain.Entities.Stammdaten.Zahlungsbedingung", "Zahlungsbedingung")
                        .WithMany()
                        .HasForeignKey("ZahlungsbedingungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Milet.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("KundeId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Strasse");

                            b1.HasKey("KundeId");

                            b1.ToTable("Kunden");

                            b1.WithOwner()
                                .HasForeignKey("KundeId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Preisliste");

                    b.Navigation("Zahlungsbedingung");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Lieferant", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Zahlungsbedingung", "Zahlungsbedingung")
                        .WithMany()
                        .HasForeignKey("ZahlungsbedingungId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Milet.Domain.ValueObjects.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<int>("LieferantId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Strasse");

                            b1.HasKey("LieferantId");

                            b1.ToTable("Lieferanten");

                            b1.WithOwner()
                                .HasForeignKey("LieferantId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Zahlungsbedingung");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Beleg", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Milet.Domain.ValueObjects.Adresse", "LieferadresseSnapshot", b1 =>
                        {
                            b1.Property<int>("BelegId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("LfAdr_Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LfAdr_Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LfAdr_Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LfAdr_Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("LfAdr_Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LfAdr_Strasse");

                            b1.HasKey("BelegId");

                            b1.ToTable("Belege");

                            b1.WithOwner()
                                .HasForeignKey("BelegId");
                        });

                    b.OwnsOne("Milet.Domain.ValueObjects.Adresse", "RechnungsadresseSnapshot", b1 =>
                        {
                            b1.Property<int>("BelegId")
                                .HasColumnType("int");

                            b1.Property<string>("Land")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("RgAdr_Land");

                            b1.Property<string>("Name1")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RgAdr_Name1");

                            b1.Property<string>("Name2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RgAdr_Name2");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RgAdr_Ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("RgAdr_Plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RgAdr_Strasse");

                            b1.HasKey("BelegId");

                            b1.ToTable("Belege");

                            b1.WithOwner()
                                .HasForeignKey("BelegId");
                        });

                    b.Navigation("Kunde");

                    b.Navigation("LieferadresseSnapshot")
                        .IsRequired();

                    b.Navigation("RechnungsadresseSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.BelegPosition", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Stammdaten.Artikel", "Artikel")
                        .WithMany()
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Milet.Domain.Entities.Verkauf.Beleg", "Beleg")
                        .WithMany("Positionen")
                        .HasForeignKey("BelegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Milet.Domain.Entities.Lager.Lagerort", "Lagerort")
                        .WithMany()
                        .HasForeignKey("LagerortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Milet.Domain.Entities.Stammdaten.MwStSatz", null)
                        .WithMany()
                        .HasForeignKey("MwStSatzId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Milet.Domain.Entities.Verkauf.BelegPosition", null)
                        .WithMany()
                        .HasForeignKey("UrsprungsPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artikel");

                    b.Navigation("Beleg");

                    b.Navigation("Lagerort");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.BelegSteuerSumme", b =>
                {
                    b.HasOne("Milet.Domain.Entities.Verkauf.Beleg", "Beleg")
                        .WithMany("Steuersummen")
                        .HasForeignKey("BelegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beleg");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Lager.Inventur", b =>
                {
                    b.Navigation("Positionen");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Stammdaten.Preisliste", b =>
                {
                    b.Navigation("Preise");
                });

            modelBuilder.Entity("Milet.Domain.Entities.Verkauf.Beleg", b =>
                {
                    b.Navigation("Positionen");

                    b.Navigation("Steuersummen");
                });
#pragma warning restore 612, 618
        }
    }
}
